version: '3.8'

services:
  app:
    container_name: app
    build: ./
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./app:/home/node/app
    depends_on:
      - db
    networks:
      - internalnet

  db:
    container_name: 'database'
    image: 'mysql:8.0'
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'
    env_file: ./.env
    networks:
      - internalnet

  adminer:
    container_name: adminer-db
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
